# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{padrino-form-errors}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kriss 'nu7hatch' Kowalik"]
  s.date = %q{2010-09-06}
  s.description = %q{Validation errors explanation done in good way for Padrino framework.}
  s.email = %q{kriss.kowalik@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/padrino-form-errors.rb",
     "lib/padrino-form-errors/generators/defaults.rb",
     "lib/padrino-form-errors/generators/templates/erb/_error_message.erb.tt",
     "lib/padrino-form-errors/generators/templates/erb/_error_messages.erb.tt",
     "lib/padrino-form-errors/generators/templates/haml/_error_message.haml.tt",
     "lib/padrino-form-errors/generators/templates/haml/_error_messages.haml.tt",
     "lib/padrino-form-errors/helpers/form_helpers.rb",
     "padrino-form-errors.gemspec"
  ]
  s.homepage = %q{http://github.com/nu7hatch/padrino-form-errors}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Form validation errors helper for Padrino}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<padrino>, [">= 0.9.14"])
    else
      s.add_dependency(%q<padrino>, [">= 0.9.14"])
    end
  else
    s.add_dependency(%q<padrino>, [">= 0.9.14"])
  end
end

